### ISSUE TITLE
编译不能通过啊

### ISSUE THREAD

**Issue by putao0525** [LeenHawk/Professional-Cpp-5th-Answer#1]
/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake --debug-server-port 62450 --debug-token-path /private/var/folders/49/8j6wwc2s40l6xp7qs8k8r_4w0000gp/T/cmake-debugtoken -S /Users/putao/code/open/c++/Professional-Cpp-5th-Answer/chapter-1/1-1 -B /Users/putao/code/open/c++/Professional-Cpp-5th-Answer/chapter-1/1-1/cmake-build-debug -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_MAKE_PROGRAM=/Applications/CLion.app/Contents/bin/ninja/mac/ninja -DCMAKE_C_COMPILER=/usr/local/opt/llvm/bin/clang -DCMAKE_CXX_COMPILER=/usr/local/opt/llvm/bin/clang++
CMake Warning (dev) at CMakeLists.txt:8 (target_sources):
  CMake's C++ module support is experimental.  It is meant only for
  experimentation and feedback to CMake developers.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
CMake Warning (dev):
  C++20 modules support via CMAKE_EXPERIMENTAL_CXX_MODULE_DYNDEP is
  experimental.  It is meant only for compiler developers to try.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_EXPERIMENTAL_CXX_SCANDEP_SOURCE
CMake Generate step failed.  Build files cannot be regenerated correctly.
Process terminated with exit code 1

**Comment by LeenHawk** [comment]
Clang needs to replace all `import std` with corresponding standard library header files such as `#include<iostream>`, or follow the [libc++guide](https://libcxx.llvm.org/Modules.html) Building libc++ with standard library modules.

In a word, Clang doesn't have standard library with standard  libc++ 17 now(Both libstdc++ or gcc). You must use MSVC.

**Comment by LeenHawk** [comment]
Add clang tutorials.
